### PR TITLE
Update to version 1.20.3

### PR DESCRIPTION
**Pull request by mlehtima**

### CODE REVIEW

**Comment by saukko** [comment]
Why merging all .spec files to one repo? In the past we have done this and each time eventually it causes more issues than helps on anything.

Also would follow what e.g. fedora does in upstream, i.e. separate repo for each package, eg. https://src.fedoraproject.org/rpms/gstreamer1/tree/rawhide and https://src.fedoraproject.org/rpms/gstreamer1-plugins-base/tree/rawhide

**Comment by mlehtima** [comment]
> Why merging all .spec files to one repo? In the past we have done this and each time eventually it causes more issues than helps on anything.
> 
> Also would follow what e.g. fedora does in upstream, i.e. separate repo for each package, eg. https://src.fedoraproject.org/rpms/gstreamer1/tree/rawhide and https://src.fedoraproject.org/rpms/gstreamer1-plugins-base/tree/rawhide

All of the plugins are now in same source repo so it seemed logical to have all spec files in same repo. Also I find it easier to update all packages when everything is in same place but if it's decided to still have each spec in separate repos I can do that also, just needs updating the submodule urls in all plugins repos to point to same place. Does fedora pull the sources from git or does it pull the releade tarballs before building?

**Comment by mlehtima** [comment]
I now kept the plugin spec files in their own repos like before.

**Review by abranson — APPROVED** [review]

**Comment by Thaodan** [comment]
> ided to still have each spec in separate repos I can do that also, just
> needs updating the submodule urls in all plugins repos to point to same
> place. Does fedora pull the sources from git or does it pull the releade
> tarballs before building?

Unless the have upstream branches plus git on some packages  like SELinux it 
is an upstream tarball.

But even for cases such as SELinux they use tarballs just generated from their 
own source.

**Pull request merged**
